
package MyElements::draw_heatmap;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'urn:RSATWS' }

__PACKAGE__->__set_name('draw_heatmap');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %request_of :ATTR(:get<request>);

__PACKAGE__->_factory(
    [ qw(        request

    ) ],
    {
        'request' => \%request_of,
    },
    {
        'request' => 'MyTypes::DrawHeatmapRequest',
    },
    {

        'request' => 'request',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::draw_heatmap

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
draw_heatmap from the namespace urn:RSATWS.





=head1 METHODS

=head2 new

 my $element = MyElements::draw_heatmap->new($data);

Constructor. The following data structure may be passed to new():

 {
   request =>  { # MyTypes::DrawHeatmapRequest
     output =>  $some_value, # string
     outformat =>  $some_value, # string
     html =>  $some_value, # int
     inputfile =>  $some_value, # string
     row_names =>  $some_value, # int
     no_text =>  $some_value, # int
     col_width =>  $some_value, # int
     row_height =>  $some_value, # int
     min =>  $some_value, # int
     max =>  $some_value, # int
     gradient =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

