package MyTypes::GetResultRequest;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ticket_of :ATTR(:get<ticket>);

__PACKAGE__->_factory(
    [ qw(        ticket

    ) ],
    {
        'ticket' => \%ticket_of,
    },
    {
        'ticket' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ticket' => 'ticket',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::GetResultRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
GetResultRequest from the namespace urn:RSATWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ticket




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::GetResultRequest
   ticket =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

