package MyTypes::MonitorResponse;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %status_of :ATTR(:get<status>);

__PACKAGE__->_factory(
    [ qw(        status

    ) ],
    {
        'status' => \%status_of,
    },
    {
        'status' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'status' => 'status',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::MonitorResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
MonitorResponse from the namespace urn:RSATWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * status




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::MonitorResponse
   status =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

