
package MyElements::peak_motifs;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'urn:RSATWS' }

__PACKAGE__->__set_name('peak_motifs');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %request_of :ATTR(:get<request>);

__PACKAGE__->_factory(
    [ qw(        request

    ) ],
    {
        'request' => \%request_of,
    },
    {
        'request' => 'MyTypes::PeakMotifsRequest',
    },
    {

        'request' => 'request',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::peak_motifs

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
peak_motifs from the namespace urn:RSATWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * request

 $element->set_request($data);
 $element->get_request();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::peak_motifs->new($data);

Constructor. The following data structure may be passed to new():

 {
   request =>  { # MyTypes::PeakMotifsRequest
     output =>  $some_value, # string
     verbosity =>  $some_value, # int
     test =>  $some_value, # string
     tmp_test_infile =>  $some_value, # string
     control =>  $some_value, # string
     tmp_control_infile =>  $some_value, # string
     max_seq_length =>  $some_value, # int
     max_motif_number =>  $some_value, # int
     ref_motif =>  $some_value, # string
     top_peaks =>  $some_value, # int
     min_length =>  $some_value, # int
     max_length =>  $some_value, # int
     markov =>  $some_value, # int
     min_markov =>  $some_value, # int
     max_markov =>  $some_value, # int
     noov =>  $some_value, # int
     class_int =>  $some_value, # int
     str =>  $some_value, # int
     graph_title =>  $some_value, # string
     image_format =>  $some_value, # string
     disco =>  $some_value, # string
     source =>  $some_value, # string
     task =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

